FROM nginx:alpine

# (Optionnel) Supprimer config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier un éventuel fichier de config Nginx perso :
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier tous vos fichiers frontend (index.html, CSS, JS, etc.)
COPY . /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
