FROM node:16-alpine

WORKDIR /usr/src/app

# Copier les fichiers package.json / package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code du backend
COPY . .

# Exposer le port du serveur Express
EXPOSE 3000

# Lancer le serveur
CMD ["node", "serveur.js"]
